name: Build Moodle App APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0

      - name: Install dependencies
        run: |
          npm install -g @ionic/cli
          npm ci

      - name: Build Ionic web assets
        run: ionic build

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Android APK
        run: |
          npx cap sync android
          cd android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: moodleapp-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
